### ISSUE TITLE
Auth: error after calling loginWith

### ISSUE THREAD

**Issue by moonofmylife** [Teranode/nuxt-module-alternatives#18]
Hi! I'm getting the following error after calling the loginWith method 

```
$auth.loginWith("laravelSanctum", form.value);
```

![image](https://user-images.githubusercontent.com/46625964/159143646-ad653723-e392-47ad-b4c6-9fec11f67e87.png)

I'm using nuxt 3, axios module (your alternative version) installed, but in [this line ](https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/runtime/schemes/cookie.ts#L76) _this.$auth.ctx.$axios_ is null

**Comment by Teranode** [comment]
@moonofmylife try the update I pushed

**Comment by moonofmylife** [comment]
Error still exists
![image](https://user-images.githubusercontent.com/46625964/159177301-ba549914-cc20-49ae-92fb-3cb1153573a8.png)

**Comment by moonofmylife** [comment]
this.axios is null in [this line ](https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/runtime/inc/request-handler.ts#L93)

**Comment by Teranode** [comment]
What does your config look like?

**Comment by moonofmylife** [comment]
@Teranode 
![image](https://user-images.githubusercontent.com/46625964/159180046-008ef8af-65b2-4352-9db2-7a534bbef7e3.png)

**Comment by Teranode** [comment]
in `buildModules` put `@nuxtjs-alt/axios` below `@nuxtjs-alt/auth`

**Comment by Teranode** [comment]
also read the auth readme for what the config for laravel sanctum would look like
